global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ner-v9-api'
    static_configs:
      - targets: ['ner-v9-api:8001']
    metrics_path: '/api/v9/ner/metrics'
